- name: "yolov10s-r20240525"
  label: "YOLO V10s THU-MIG"
  platform: "od"
  model_type: "yolov10"
  config_path: ":/yolov10s.yaml"
- name: "yolov9e-r20240224"
  label: "YOLOv9e WongKinYiu"
  platform: "od"
  model_type: "yolov9"
  config_path: ":/yolov9e.yaml"
- name: "segment_anything_vit_b-r20230810"
  label: "Segment Anything (ViT-Base)"
  platform: "seg"
  model_type: "sam"
  config_path: ":/segment_anything_vit_b.yaml"