- name: "yolov10s-r20240525"
  label: "YOLO V10s THU-MIG"
  platform: "od"
  model_type: "YOLOv10"
  config_path: ":/yolov10s.yaml"
- name: "yolov9e-r20240224"
  label: "YOLOv9e WongKinYiu"
  platform: "od"
  model_type: "YOLOv9"
  config_path: ":/yolov9e.yaml"
- name: "yolov8s-r20230520"
  label: "YOLOv8s Ultralytics"
  platform: "od"
  model_type: "YOLOv8"
  config_path: ":/yolov8s.yaml"
- name: "yolov7-r20230520"
  label: "YOLOv7 WongKinYiu"
  platform: "od"
  model_type: "YOLOv7"
  config_path: ":/yolov7.yaml"
- name: "yolov6s-r20230520"
  label: "YOLOv6s MeiTuan"
  platform: "od"
  model_type: "YOLOv6"
  config_path: ":/yolov6s.yaml"
- name: "yolov5s-r20230520"
  label: "YOLOv5s Ultralytics"
  platform: "od"
  model_type: "YOLOv5"
  config_path: ":/yolov5s.yaml"
- name: "segment_anything_vit_b-r20230810"
  label: "Segment Anything (ViT-Base)"
  platform: "seg"
  model_type: "SegmentAnything"
  config_path: ":/segment_anything_vit_b.yaml"