encoder_model_path: https://github.com/momentNi/SemiLabelTool/releases/download/v0.1.0/sam_vit_b_01ec64.encoder.onnx
decoder_model_path: https://github.com/momentNi/SemiLabelTool/releases/download/v0.1.0/sam_vit_b_01ec64.decoder.onnx
input_size: 1024
max_width: 1024
max_height: 682
