#
# Template for custom models config yaml
#

# Model name, must be unique
name: Your model name
# Labels that indicates extra model info (e.g. author, version ...)
label: Model Author 1.0.0
# Platform of model running. Must be `od`(object detection) or `seg`(segmentation)
platform: od
# Model Type Must be `YOLOv5` or `YOLOv6` or `YOLOv7` or `YOLOv8` or `YOLOv9` or `YOLOv10` or `Segmentation`
model_type: YOLOv6
# The path of your model weight. The value can either be URL or local file path.
# The key value for YOLO is `model_path`.
# The key value for Segmentation is `encoder_model_path` and `decoder_model_path.
#model_path: https://github.com/momentNi/SemiLabelTool/releases/download/v0.1.0/yolov9e.onnx
#encoder_model_path: https://github.com/momentNi/SemiLabelTool/releases/download/v0.1.0/sam_vit_b_01ec64.encoder.onnx
#decoder_model_path: https://github.com/momentNi/SemiLabelTool/releases/download/v0.1.0/sam_vit_b_01ec64.decoder.onnx

# Below here you can add whatever configs you want to support your model running.
